#This is the Ion module of Numworks.

from keyboard import *

KEY_LEFT=0
KEY_UP=1
KEY_DOWN=2
KEY_RIGHT=3
KEY_OK=4
KEY_BACK=5
KEY_HOME=6
KEY_ONOFF=7
KEY_SHIFT=8
KEY_ALPHA=9
KEY_XNT=10
KEY_VAR=11
KEY_TOOLBOX=12
KEY_BACKSPACE=13
KEY_LN=14
KEY_LOG=15
KEY_IMAGINARY=16
KEY_COMMA=17
KEY_POWER=18
KEY_SINE=19
KEY_COSINE=20
KEY_TANGENT=21
KEY_PI=22
KEY_SQRT=23
KEY_SQUARE=24
KEY_SEVEN=25
KEY_EIGHT=26
KEY_NINE=27
KEY_LEFTPARENTHESIS=28
KEY_RIGHTPARENTHESIS=29
KEY_FOUR=30
KEY_FIVE=31
KEY_SIX=32
KEY_MULTIPLICATION=33
KEY_DIVISION=34
KEY_ONE=35
KEY_TWO=36
KEY_THREE=37
KEY_PLUS=38
KEY_MINUS=39
KEY_DOT=40
KEY_EE=41
KEY_ANS=42
KEY_EXE=43

KEYS_=[4,8,2,6,"\n","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","\n"]

def keydown(k):
  return is_pressed(KEYS_[k])
